name = "Perm"
grammar = "perm"
path_suffixes = ["perm"]
line_comments = "// "
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
]
