id = "perm"
name = "Perm"
description = "Perm schema support for Permify schemas."
version = "0.0.1"
schema_version = 1
authors = ["Steven Turturo <steven@dryheatlabs.com>"]
repository = "https://github.com/theoriginalstove/permify.zed"

[grammars.perm]
repository = "https://github.com/theoriginalstove/tree-sitter-perm"
commit = "dd24ae4abcc41c0a0a1526835a9abfe8ce96ff39"
